### PR TITLE
added 404 page #15

### LINKED ISSUE #15: 404 page missing
I would like to add a "404 page not found" page . If the redirect url is not present then this page will be shown instead of showing errors on page which is not good for user experience
@AyushTripathiIITP 
the page i am talking about will look like this :

Screenshot (127)

### PR DESCRIPTION
**Pull request by Yash-Ainapure**
Closes #15 
Screenshot (148)

### CODE REVIEW

**Comment by AyushTripathiIITP** [comment]
good job @Yash-Ainapure

**Comment by Yash-Ainapure** [comment]
> good job @Yash-Ainapure

thanks 😊

**Comment by Yash-Ainapure** [comment]
@AyushTripathiIITP , 1 point for the issue i created hasn't given the points

**Comment by AyushTripathiIITP** [comment]
I have now updated your points tally

**Pull request merged**
