### PR TITLE
Create README.md Closes #1

### LINKED ISSUE #1: Add a README file for this project
https://drive.google.com/file/d/1XRMFvvfmqeTt9HS9IExU-yEA2IULeQ_2/view?usp=sharing

Download this video and add it in readme.md file also add all basic tools that are being used in this project
Add all necessary details that you might think good.
Make it as appealing as possible

### PR DESCRIPTION
**Pull request by Yash-Ainapure**
Created a README.md file for this repository
Feel free to tell if some changes to be made in the file

Would love to contribute more ,Thank you.

### CODE REVIEW

**Comment by Yash-Ainapure** [comment]
Forgot to mention #1 
make sure to add this contribution towards Codepeak event 
Thanks

**Comment by Yash-Ainapure** [comment]
Heyy @AyushTripathiIITP  ,how can i get the codepeak '23 points ?
is this repo included in codepeak event?

**Comment by Yash-Ainapure** [comment]
Heyy @AyushTripathiIITP ,could you give me the codepeak points please

**Comment by AyushTripathiIITP** [comment]
Yes @Yash-Ainapure I have talked with the organizers they will soon allot you the points dont worry

**Comment by Yash-Ainapure** [comment]
@AyushTripathiIITP  ,I didn't still didn't get the points

**Pull request merged**
